version: 2.1
orbs:
    node: circleci/node@1.1.6
    aws-cli: circleci/aws-cli@1.0.0

jobs:
    build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm run build
                      - run: npm test
    deploy:
        executor: aws-cli/default
        steps:
            - checkout
            - aws-cli/setup
            - run:
                  name: "Show AWS CLI and Amplify Versions"
                  command: |
                      aws --version
                      amplify --version
            - run:
                  name: "Checkout Amplify prod Environment"
                  command: |
                      amplify env list
                      amplify init --amplify "{\"envName\":\"prod\"}" --providers "{\"awscloudformation\":{\"useProfile\":true,\"profileName\":\"default\"}}" --yes
            - run:
                  name: "Deploy to prod"
                  command: |
                      amplify publish --invalidateCloudFront --codegen "{\"generateCode\":false}" -- yes
workflows:
    build-and-test:
        jobs:
            - build-and-test
    deploy:
        jobs:
            - deploy
