import moment from "moment";

const yearsArray = () => {
    const currentYear = moment().year();
    let startYear = currentYear - 30;
    let result = [{ value: "", label: "Año" }];
    while (startYear <= currentYear) {
        result.push({ value: `${startYear}`, label: `${startYear}` });
        startYear++;
    }
    return result;
};

export const years = yearsArray();

export const types = [
    { value: "Vehículo Turbo", label: "Vehículo Turbo" },
    { value: "Camión Sencillo", label: "Camión Sencillo" },
    { value: "Doble Troque", label: "Doble Troque" },
    { value: "Cuatro Manos", label: "Cuatro Manos" },
    { value: "Minimula", label: "Minimula" },
    { value: "Tractomula 2 Troques", label: "Tractomula 2 Troques" },
    { value: "Tractomula 3 Troques", label: "Tractomula 3 Troques" },
];

export const departments = [
    { value: "Antioquia", label: "Antioquia" },
    { value: "Santander", label: "Santander" },
    { value: "Sucre", label: "Sucre" },
    { value: "Casanare", label: "Casanare" },
    { value: "Norte de Santander", label: "Norte de Santander" },
    { value: "Cundinamarca", label: "Cundinamarca" },
    { value: "Vaupés", label: "Vaupés" },
    { value: "Córdoba", label: "Córdoba" },
    { value: "Putumayo", label: "Putumayo" },
    { value: "Nariño", label: "Nariño" },
    { value: "Atlántico", label: "Atlántico" },
    { value: "Bolívar", label: "Bolívar" },
    { value: "Valle del Cauca", label: "Valle del Cauca" },
    { value: "Tolima", label: "Tolima" },
    { value: "Caquetá", label: "Caquetá" },
    { value: "Amazonas", label: "Amazonas" },
    { value: "Boyacá", label: "Boyacá" },
    { value: "Cauca", label: "Cauca" },
    { value: "Chocó", label: "Chocó" },
    { value: "Caldas", label: "Caldas" },
    { value: "Magdalena", label: "Magdalena" },
    { value: "Cesar", label: "Cesar" },
    { value: "Quindío", label: "Quindío" },
    { value: "Meta", label: "Meta" },
    { value: "Huila", label: "Huila" },
    { value: "La Guajira", label: "La Guajira" },
    { value: "Risaralda", label: "Risaralda" },
    { value: "Arauca", label: "Arauca" },
    { value: "Guainía", label: "Guainía" },
    { value: "Vichada", label: "Vichada" },
    { value: "Guaviare", label: "Guaviare" },
    { value: "Bogotá D.C.", label: "Bogotá D.C." },
    {
        value: "Archipiélago de San Andrés, Providencia y Santa Catalina",
        label: "Archipiélago de San Andrés, Providencia y Santa Catalina",
    },
];

export const cities = [
    { department: "Antioquia", city: "Medellín" },
    { department: "Antioquia", city: "Abejorral" },
    { department: "Antioquia", city: "Abriaquí" },
    { department: "Antioquia", city: "Alejandría" },
    { department: "Antioquia", city: "Amagá" },
    { department: "Antioquia", city: "Amalfi" },
    { department: "Antioquia", city: "Andes" },
    { department: "Antioquia", city: "Angelópolis" },
    { department: "Antioquia", city: "Angostura" },
    { department: "Antioquia", city: "Anorí" },
    { department: "Santander", city: "Chimá" },
    { department: "Antioquia", city: "Anza" },
    { department: "Antioquia", city: "Apartadó" },
    { department: "Antioquia", city: "Arboletes" },
    { department: "Antioquia", city: "Argelia" },
    { department: "Antioquia", city: "Armenia" },
    { department: "Antioquia", city: "Barbosa" },
    { department: "Antioquia", city: "Bello" },
    { department: "Antioquia", city: "Betania" },
    { department: "Antioquia", city: "Betulia" },
    { department: "Antioquia", city: "Ciudad Bolívar" },
    { department: "Antioquia", city: "Briceño" },
    { department: "Antioquia", city: "Buriticá" },
    { department: "Antioquia", city: "Cáceres" },
    { department: "Antioquia", city: "Caicedo" },
    { department: "Antioquia", city: "Caldas" },
    { department: "Antioquia", city: "Campamento" },
    { department: "Antioquia", city: "Cañasgordas" },
    { department: "Antioquia", city: "Caracolí" },
    { department: "Antioquia", city: "Caramanta" },
    { department: "Antioquia", city: "Carepa" },
    { department: "Sucre", city: "Sampués" },
    { department: "Antioquia", city: "Carolina" },
    { department: "Antioquia", city: "Caucasia" },
    { department: "Antioquia", city: "Chigorodó" },
    { department: "Antioquia", city: "Cisneros" },
    { department: "Antioquia", city: "Cocorná" },
    { department: "Antioquia", city: "Concepción" },
    { department: "Antioquia", city: "Concordia" },
    { department: "Antioquia", city: "Copacabana" },
    { department: "Antioquia", city: "Dabeiba" },
    { department: "Antioquia", city: "Don Matías" },
    { department: "Antioquia", city: "Ebéjico" },
    { department: "Antioquia", city: "El Bagre" },
    { department: "Antioquia", city: "Entrerrios" },
    { department: "Antioquia", city: "Envigado" },
    { department: "Antioquia", city: "Fredonia" },
    { department: "Antioquia", city: "Giraldo" },
    { department: "Antioquia", city: "Girardota" },
    { department: "Antioquia", city: "Gómez Plata" },
    { department: "Casanare", city: "Nunchía" },
    { department: "Antioquia", city: "Guadalupe" },
    { department: "Antioquia", city: "Guarne" },
    { department: "Antioquia", city: "Guatapé" },
    { department: "Antioquia", city: "Heliconia" },
    { department: "Antioquia", city: "Hispania" },
    { department: "Antioquia", city: "Itagui" },
    { department: "Antioquia", city: "Ituango" },
    { department: "Norte de Santander", city: "Pamplona" },
    { department: "Antioquia", city: "Jericó" },
    { department: "Antioquia", city: "La Ceja" },
    { department: "Antioquia", city: "La Estrella" },
    { department: "Antioquia", city: "La Pintada" },
    { department: "Antioquia", city: "La Unión" },
    { department: "Antioquia", city: "Liborina" },
    { department: "Antioquia", city: "Maceo" },
    { department: "Antioquia", city: "Marinilla" },
    { department: "Antioquia", city: "Montebello" },
    { department: "Antioquia", city: "Murindó" },
    { department: "Antioquia", city: "Mutatá" },
    { department: "Antioquia", city: "Nariño" },
    { department: "Antioquia", city: "Necoclí" },
    { department: "Antioquia", city: "Nechí" },
    { department: "Antioquia", city: "Olaya" },
    { department: "Antioquia", city: "Peñol" },
    { department: "Antioquia", city: "Peque" },
    { department: "Antioquia", city: "Pueblorrico" },
    { department: "Antioquia", city: "Puerto Berrío" },
    { department: "Antioquia", city: "Puerto Nare" },
    { department: "Antioquia", city: "Puerto Triunfo" },
    { department: "Antioquia", city: "Remedios" },
    { department: "Antioquia", city: "Retiro" },
    { department: "Antioquia", city: "Rionegro" },
    { department: "Antioquia", city: "Sabanalarga" },
    { department: "Antioquia", city: "Sabaneta" },
    { department: "Antioquia", city: "Salgar" },
    { department: "Cundinamarca", city: "Albán" },
    { department: "Vaupés", city: "Yavaraté" },
    { department: "Antioquia", city: "San Francisco" },
    { department: "Antioquia", city: "San Jerónimo" },
    { department: "Córdoba", city: "Montelíbano" },
    { department: "Putumayo", city: "Puerto Asís" },
    { department: "Antioquia", city: "San Luis" },
    { department: "Antioquia", city: "San Pedro" },
    { department: "Sucre", city: "Corozal" },
    { department: "Antioquia", city: "San Rafael" },
    { department: "Antioquia", city: "San Roque" },
    { department: "Antioquia", city: "San Vicente" },
    { department: "Antioquia", city: "Santa Bárbara" },
    { department: "Nariño", city: "Buesaco" },
    { department: "Antioquia", city: "Santo Domingo" },
    { department: "Antioquia", city: "El Santuario" },
    { department: "Antioquia", city: "Segovia" },
    { department: "Antioquia", city: "Sopetrán" },
    { department: "Antioquia", city: "Támesis" },
    { department: "Antioquia", city: "Tarazá" },
    { department: "Antioquia", city: "Tarso" },
    { department: "Antioquia", city: "Titiribí" },
    { department: "Antioquia", city: "Toledo" },
    { department: "Antioquia", city: "Turbo" },
    { department: "Antioquia", city: "Uramita" },
    { department: "Antioquia", city: "Urrao" },
    { department: "Antioquia", city: "Valdivia" },
    { department: "Antioquia", city: "Valparaíso" },
    { department: "Antioquia", city: "Vegachí" },
    { department: "Antioquia", city: "Venecia" },
    { department: "Casanare", city: "Maní" },
    { department: "Antioquia", city: "Yalí" },
    { department: "Antioquia", city: "Yarumal" },
    { department: "Antioquia", city: "Yolombó" },
    { department: "Antioquia", city: "Yondó" },
    { department: "Antioquia", city: "Zaragoza" },
    { department: "Atlántico", city: "Barranquilla" },
    { department: "Atlántico", city: "Baranoa" },
    { department: "Bolívar", city: "El Peñón" },
    { department: "Atlántico", city: "Candelaria" },
    { department: "Atlántico", city: "Galapa" },
    { department: "Valle del Cauca", city: "Tuluá" },
    { department: "Tolima", city: "Casabianca" },
    { department: "Atlántico", city: "Luruaco" },
    { department: "Atlántico", city: "Malambo" },
    { department: "Atlántico", city: "Manatí" },
    { department: "Cundinamarca", city: "Anolaima" },
    { department: "Atlántico", city: "Piojó" },
    { department: "Atlántico", city: "Polonuevo" },
    { department: "Cundinamarca", city: "Chía" },
    { department: "Nariño", city: "San Andrés de Tumaco" },
    { department: "Atlántico", city: "Sabanagrande" },
    { department: "Atlántico", city: "Sabanalarga" },
    { department: "Atlántico", city: "Santa Lucía" },
    { department: "Atlántico", city: "Santo Tomás" },
    { department: "Atlántico", city: "Soledad" },
    { department: "Atlántico", city: "Suan" },
    { department: "Atlántico", city: "Tubará" },
    { department: "Atlántico", city: "Usiacurí" },
    { department: "Caquetá", city: "Milán" },
    { department: "Santander", city: "Capitanejo" },
    { department: "Bolívar", city: "Achí" },
    { department: "Tolima", city: "Anzoátegui" },
    { department: "Bolívar", city: "Arenal" },
    { department: "Bolívar", city: "Arjona" },
    { department: "Bolívar", city: "Arroyohondo" },
    { department: "Valle del Cauca", city: "Florida" },
    { department: "Bolívar", city: "Calamar" },
    { department: "Bolívar", city: "Cantagallo" },
    { department: "Bolívar", city: "Cicuco" },
    { department: "Bolívar", city: "Córdoba" },
    { department: "Bolívar", city: "Clemencia" },
    { department: "Atlántico", city: "Repelón" },
    { department: "Bolívar", city: "El Guamo" },
    { department: "Antioquia", city: "Frontino" },
    { department: "Bolívar", city: "Magangué" },
    { department: "Bolívar", city: "Mahates" },
    { department: "Bolívar", city: "Margarita" },
    { department: "Bolívar", city: "Montecristo" },
    { department: "Bolívar", city: "Mompós" },
    { department: "Bolívar", city: "Morales" },
    { department: "Bolívar", city: "Norosí" },
    { department: "Bolívar", city: "Pinillos" },
    { department: "Bolívar", city: "Regidor" },
    { department: "Bolívar", city: "Río Viejo" },
    { department: "Bolívar", city: "San Estanislao" },
    { department: "Bolívar", city: "San Fernando" },
    { department: "Cundinamarca", city: "El Peñón" },
    { department: "Norte de Santander", city: "Pamplonita" },
    { department: "Bolívar", city: "San Juan Nepomuceno" },
    { department: "Amazonas", city: "Miriti Paraná" },
    { department: "Casanare", city: "Támara" },
    { department: "Bolívar", city: "Santa Catalina" },
    { department: "Bolívar", city: "Santa Rosa" },
    { department: "Boyacá", city: "Tibasosa" },
    { department: "Bolívar", city: "Simití" },
    { department: "Bolívar", city: "Soplaviento" },
    { department: "Bolívar", city: "Talaigua Nuevo" },
    { department: "Bolívar", city: "Tiquisio" },
    { department: "Bolívar", city: "Turbaco" },
    { department: "Bolívar", city: "Turbaná" },
    { department: "Bolívar", city: "Villanueva" },
    { department: "Cauca", city: "Páez" },
    { department: "Boyacá", city: "Tunja" },
    { department: "Boyacá", city: "Almeida" },
    { department: "Boyacá", city: "Aquitania" },
    { department: "Boyacá", city: "Arcabuco" },
    { department: "Tolima", city: "Ibagué" },
    { department: "Boyacá", city: "Berbeo" },
    { department: "Boyacá", city: "Betéitiva" },
    { department: "Boyacá", city: "Boavita" },
    { department: "Boyacá", city: "Boyacá" },
    { department: "Boyacá", city: "Briceño" },
    { department: "Boyacá", city: "Buena Vista" },
    { department: "Boyacá", city: "Busbanzá" },
    { department: "Boyacá", city: "Caldas" },
    { department: "Boyacá", city: "Campohermoso" },
    { department: "Boyacá", city: "Cerinza" },
    { department: "Boyacá", city: "Chinavita" },
    { department: "Boyacá", city: "Chiquinquirá" },
    { department: "Boyacá", city: "Chiscas" },
    { department: "Boyacá", city: "Chita" },
    { department: "Boyacá", city: "Chitaraque" },
    { department: "Boyacá", city: "Chivatá" },
    { department: "Boyacá", city: "Cómbita" },
    { department: "Boyacá", city: "Coper" },
    { department: "Boyacá", city: "Corrales" },
    { department: "Boyacá", city: "Covarachía" },
    { department: "Boyacá", city: "Cubará" },
    { department: "Boyacá", city: "Cucaita" },
    { department: "Boyacá", city: "Cuítiva" },
    { department: "Boyacá", city: "Chíquiza" },
    { department: "Boyacá", city: "Chivor" },
    { department: "Boyacá", city: "Duitama" },
    { department: "Boyacá", city: "El Cocuy" },
    { department: "Boyacá", city: "El Espino" },
    { department: "Boyacá", city: "Firavitoba" },
    { department: "Boyacá", city: "Floresta" },
    { department: "Boyacá", city: "Gachantivá" },
    { department: "Boyacá", city: "Gameza" },
    { department: "Boyacá", city: "Garagoa" },
    { department: "Boyacá", city: "Guacamayas" },
    { department: "Boyacá", city: "Guateque" },
    { department: "Boyacá", city: "Guayatá" },
    { department: "Boyacá", city: "Güicán" },
    { department: "Boyacá", city: "Iza" },
    { department: "Boyacá", city: "Jenesano" },
    { department: "Boyacá", city: "Jericó" },
    { department: "Boyacá", city: "Labranzagrande" },
    { department: "Boyacá", city: "La Capilla" },
    { department: "Boyacá", city: "La Victoria" },
    { department: "Atlántico", city: "Puerto Colombia" },
    { department: "Nariño", city: "Belén" },
    { department: "Boyacá", city: "Macanal" },
    { department: "Boyacá", city: "Maripí" },
    { department: "Boyacá", city: "Miraflores" },
    { department: "Boyacá", city: "Mongua" },
    { department: "Boyacá", city: "Monguí" },
    { department: "Boyacá", city: "Moniquirá" },
    { department: "Boyacá", city: "Muzo" },
    { department: "Boyacá", city: "Nobsa" },
    { department: "Boyacá", city: "Nuevo Colón" },
    { department: "Boyacá", city: "Oicatá" },
    { department: "Boyacá", city: "Otanche" },
    { department: "Boyacá", city: "Pachavita" },
    { department: "Boyacá", city: "Páez" },
    { department: "Boyacá", city: "Paipa" },
    { department: "Boyacá", city: "Pajarito" },
    { department: "Boyacá", city: "Panqueba" },
    { department: "Boyacá", city: "Pauna" },
    { department: "Boyacá", city: "Paya" },
    { department: "Cundinamarca", city: "Sopó" },
    { department: "Boyacá", city: "Pesca" },
    { department: "Boyacá", city: "Pisba" },
    { department: "Boyacá", city: "Puerto Boyacá" },
    { department: "Boyacá", city: "Quípama" },
    { department: "Boyacá", city: "Ramiriquí" },
    { department: "Boyacá", city: "Ráquira" },
    { department: "Boyacá", city: "Rondón" },
    { department: "Boyacá", city: "Saboyá" },
    { department: "Boyacá", city: "Sáchica" },
    { department: "Boyacá", city: "Samacá" },
    { department: "Boyacá", city: "San Eduardo" },
    { department: "Chocó", city: "Carmen del Darien" },
    { department: "Cundinamarca", city: "Gama" },
    { department: "Boyacá", city: "San Mateo" },
    { department: "Cundinamarca", city: "Sasaima" },
    { department: "Nariño", city: "Chachagüí" },
    { department: "Boyacá", city: "Santana" },
    { department: "Boyacá", city: "Santa María" },
    { department: "Norte de Santander", city: "Cúcuta" },
    { department: "Boyacá", city: "Santa Sofía" },
    { department: "Boyacá", city: "Sativanorte" },
    { department: "Boyacá", city: "Sativasur" },
    { department: "Boyacá", city: "Siachoque" },
    { department: "Boyacá", city: "Soatá" },
    { department: "Boyacá", city: "Socotá" },
    { department: "Boyacá", city: "Socha" },
    { department: "Boyacá", city: "Sogamoso" },
    { department: "Boyacá", city: "Somondoco" },
    { department: "Boyacá", city: "Sora" },
    { department: "Boyacá", city: "Sotaquirá" },
    { department: "Boyacá", city: "Soracá" },
    { department: "Boyacá", city: "Susacón" },
    { department: "Boyacá", city: "Sutamarchán" },
    { department: "Boyacá", city: "Sutatenza" },
    { department: "Boyacá", city: "Tasco" },
    { department: "Boyacá", city: "Tenza" },
    { department: "Boyacá", city: "Tibaná" },
    { department: "Boyacá", city: "Tinjacá" },
    { department: "Boyacá", city: "Tipacoque" },
    { department: "Boyacá", city: "Toca" },
    { department: "Bolívar", city: "Cartagena" },
    { department: "Boyacá", city: "Tópaga" },
    { department: "Boyacá", city: "Tota" },
    { department: "Boyacá", city: "Turmequé" },
    { department: "Antioquia", city: "Granada" },
    { department: "Boyacá", city: "Tutazá" },
    { department: "Boyacá", city: "Umbita" },
    { department: "Boyacá", city: "Ventaquemada" },
    { department: "Boyacá", city: "Viracachá" },
    { department: "Boyacá", city: "Zetaquira" },
    { department: "Caldas", city: "Manizales" },
    { department: "Caldas", city: "Aguadas" },
    { department: "Caldas", city: "Anserma" },
    { department: "Caldas", city: "Aranzazu" },
    { department: "Caldas", city: "Belalcázar" },
    { department: "Caldas", city: "Chinchiná" },
    { department: "Caldas", city: "Filadelfia" },
    { department: "Caldas", city: "La Dorada" },
    { department: "Caldas", city: "La Merced" },
    { department: "Caldas", city: "Manzanares" },
    { department: "Caldas", city: "Marmato" },
    { department: "Caldas", city: "Marulanda" },
    { department: "Caldas", city: "Neira" },
    { department: "Caldas", city: "Norcasia" },
    { department: "Caldas", city: "Pácora" },
    { department: "Caldas", city: "Palestina" },
    { department: "Caldas", city: "Pensilvania" },
    { department: "Caldas", city: "Riosucio" },
    { department: "Caldas", city: "Risaralda" },
    { department: "Caldas", city: "Salamina" },
    { department: "Caldas", city: "Samaná" },
    { department: "Caldas", city: "San José" },
    { department: "Caldas", city: "Supía" },
    { department: "Caldas", city: "Victoria" },
    { department: "Caldas", city: "Villamaría" },
    { department: "Caldas", city: "Viterbo" },
    { department: "Caquetá", city: "Florencia" },
    { department: "Caquetá", city: "Albania" },
    { department: "Magdalena", city: "Santa Bárbara de Pinto" },
    { department: "Bolívar", city: "María la Baja" },
    { department: "Caquetá", city: "Curillo" },
    { department: "Caquetá", city: "El Doncello" },
    { department: "Caquetá", city: "El Paujil" },
    { department: "Caquetá", city: "Morelia" },
    { department: "Caquetá", city: "Puerto Rico" },
    { department: "Caquetá", city: "La Montañita" },
    { department: "Caquetá", city: "San Vicente del Caguán" },
    { department: "Caquetá", city: "Solano" },
    { department: "Caquetá", city: "Solita" },
    { department: "Caquetá", city: "Valparaíso" },
    { department: "Cauca", city: "Popayán" },
    { department: "Cauca", city: "Almaguer" },
    { department: "Cauca", city: "Argelia" },
    { department: "Cauca", city: "Balboa" },
    { department: "Cauca", city: "Bolívar" },
    { department: "Cauca", city: "Buenos Aires" },
    { department: "Cauca", city: "Cajibío" },
    { department: "Cauca", city: "Caldono" },
    { department: "Cauca", city: "Caloto" },
    { department: "Cauca", city: "Corinto" },
    { department: "Cauca", city: "El Tambo" },
    { department: "Cauca", city: "Florencia" },
    { department: "Cauca", city: "Guachené" },
    { department: "Cauca", city: "Guapi" },
    { department: "Cauca", city: "Inzá" },
    { department: "Cauca", city: "Jambaló" },
    { department: "Cauca", city: "La Sierra" },
    { department: "Cauca", city: "La Vega" },
    { department: "Cauca", city: "López" },
    { department: "Cauca", city: "Mercaderes" },
    { department: "Cauca", city: "Miranda" },
    { department: "Cauca", city: "Morales" },
    { department: "Cauca", city: "Padilla" },
    { department: "Cauca", city: "Patía" },
    { department: "Cauca", city: "Piamonte" },
    { department: "Cauca", city: "Piendamó" },
    { department: "Cauca", city: "Puerto Tejada" },
    { department: "Cauca", city: "Puracé" },
    { department: "Cauca", city: "Rosas" },
    { department: "Santander", city: "El Peñón" },
    { department: "Antioquia", city: "Jardín" },
    { department: "Cauca", city: "Santa Rosa" },
    { department: "Cauca", city: "Silvia" },
    { department: "Cauca", city: "Sotara" },
    { department: "Cauca", city: "Suárez" },
    { department: "Cauca", city: "Sucre" },
    { department: "Cauca", city: "Timbío" },
    { department: "Cauca", city: "Timbiquí" },
    { department: "Cauca", city: "Toribio" },
    { department: "Cauca", city: "Totoró" },
    { department: "Cauca", city: "Villa Rica" },
    { department: "Cesar", city: "Valledupar" },
    { department: "Cesar", city: "Aguachica" },
    { department: "Cesar", city: "Agustín Codazzi" },
    { department: "Cesar", city: "Astrea" },
    { department: "Cesar", city: "Becerril" },
    { department: "Cesar", city: "Bosconia" },
    { department: "Cesar", city: "Chimichagua" },
    { department: "Cesar", city: "Chiriguaná" },
    { department: "Cesar", city: "Curumaní" },
    { department: "Cesar", city: "El Copey" },
    { department: "Cesar", city: "El Paso" },
    { department: "Cesar", city: "Gamarra" },
    { department: "Cesar", city: "González" },
    { department: "Cesar", city: "La Gloria" },
    { department: "Valle del Cauca", city: "Jamundí" },
    { department: "Cesar", city: "Manaure" },
    { department: "Cesar", city: "Pailitas" },
    { department: "Cesar", city: "Pelaya" },
    { department: "Cesar", city: "Pueblo Bello" },
    { department: "Chocó", city: "Tadó" },
    { department: "Cesar", city: "La Paz" },
    { department: "Cesar", city: "San Alberto" },
    { department: "Cesar", city: "San Diego" },
    { department: "Cesar", city: "San Martín" },
    { department: "Cesar", city: "Tamalameque" },
    { department: "Córdoba", city: "Montería" },
    { department: "Córdoba", city: "Ayapel" },
    { department: "Córdoba", city: "Buenavista" },
    { department: "Córdoba", city: "Canalete" },
    { department: "Córdoba", city: "Cereté" },
    { department: "Córdoba", city: "Chimá" },
    { department: "Córdoba", city: "Chinú" },
    { department: "Casanare", city: "Orocué" },
    { department: "Córdoba", city: "Cotorra" },
    { department: "Tolima", city: "Líbano" },
    { department: "Córdoba", city: "Lorica" },
    { department: "Córdoba", city: "Los Córdobas" },
    { department: "Córdoba", city: "Momil" },
    { department: "Córdoba", city: "Moñitos" },
    { department: "Córdoba", city: "Planeta Rica" },
    { department: "Córdoba", city: "Pueblo Nuevo" },
    { department: "Córdoba", city: "Puerto Escondido" },
    { department: "Cundinamarca", city: "Yacopí" },
    { department: "Córdoba", city: "Purísima" },
    { department: "Córdoba", city: "Sahagún" },
    { department: "Córdoba", city: "San Andrés Sotavento" },
    { department: "Córdoba", city: "San Antero" },
    { department: "Quindío", city: "Calarcá" },
    { department: "Antioquia", city: "Sonsón" },
    { department: "Norte de Santander", city: "El Carmen" },
    { department: "Córdoba", city: "San Pelayo" },
    { department: "Córdoba", city: "Tierralta" },
    { department: "Córdoba", city: "Tuchín" },
    { department: "Córdoba", city: "Valencia" },
    { department: "Tolima", city: "Lérida" },
    { department: "Cundinamarca", city: "Anapoima" },
    { department: "Cundinamarca", city: "Arbeláez" },
    { department: "Cundinamarca", city: "Beltrán" },
    { department: "Cundinamarca", city: "Bituima" },
    { department: "Cundinamarca", city: "Bojacá" },
    { department: "Cundinamarca", city: "Cabrera" },
    { department: "Cundinamarca", city: "Cachipay" },
    { department: "Cundinamarca", city: "Cajicá" },
    { department: "Cundinamarca", city: "Caparrapí" },
    { department: "Cundinamarca", city: "Caqueza" },
    { department: "Córdoba", city: "La Apartada" },
    { department: "Cundinamarca", city: "Chaguaní" },
    { department: "Cundinamarca", city: "Chipaque" },
    { department: "Cundinamarca", city: "Choachí" },
    { department: "Cundinamarca", city: "Chocontá" },
    { department: "Cundinamarca", city: "Cogua" },
    { department: "Cundinamarca", city: "Cota" },
    { department: "Cundinamarca", city: "Cucunubá" },
    { department: "Cundinamarca", city: "El Colegio" },
    { department: "Cundinamarca", city: "El Rosal" },
    { department: "Cundinamarca", city: "Fomeque" },
    { department: "Cundinamarca", city: "Fosca" },
    { department: "Cundinamarca", city: "Funza" },
    { department: "Cundinamarca", city: "Fúquene" },
    { department: "Cundinamarca", city: "Gachala" },
    { department: "Cundinamarca", city: "Gachancipá" },
    { department: "Cundinamarca", city: "Gachetá" },
    { department: "Bolívar", city: "San Cristóbal" },
    { department: "Cundinamarca", city: "Girardot" },
    { department: "Cundinamarca", city: "Granada" },
    { department: "Cundinamarca", city: "Guachetá" },
    { department: "Cundinamarca", city: "Guaduas" },
    { department: "Cundinamarca", city: "Guasca" },
    { department: "Cundinamarca", city: "Guataquí" },
    { department: "Cundinamarca", city: "Guatavita" },
    { department: "Cundinamarca", city: "Fusagasugá" },
    { department: "Cundinamarca", city: "Guayabetal" },
    { department: "Cundinamarca", city: "Gutiérrez" },
    { department: "Cundinamarca", city: "Jerusalén" },
    { department: "Cundinamarca", city: "Junín" },
    { department: "Cundinamarca", city: "La Calera" },
    { department: "Cundinamarca", city: "La Mesa" },
    { department: "Cundinamarca", city: "La Palma" },
    { department: "Cundinamarca", city: "La Peña" },
    { department: "Cundinamarca", city: "La Vega" },
    { department: "Cundinamarca", city: "Lenguazaque" },
    { department: "Cundinamarca", city: "Macheta" },
    { department: "Cundinamarca", city: "Madrid" },
    { department: "Cundinamarca", city: "Manta" },
    { department: "Cundinamarca", city: "Medina" },
    { department: "Cundinamarca", city: "Mosquera" },
    { department: "Cundinamarca", city: "Nariño" },
    { department: "Cundinamarca", city: "Nemocón" },
    { department: "Cundinamarca", city: "Nilo" },
    { department: "Cundinamarca", city: "Nimaima" },
    { department: "Cundinamarca", city: "Nocaima" },
    { department: "Cundinamarca", city: "Venecia" },
    { department: "Cundinamarca", city: "Pacho" },
    { department: "Cundinamarca", city: "Paime" },
    { department: "Cundinamarca", city: "Pandi" },
    { department: "Cundinamarca", city: "Paratebueno" },
    { department: "Cundinamarca", city: "Pasca" },
    { department: "Cundinamarca", city: "Puerto Salgar" },
    { department: "Cundinamarca", city: "Pulí" },
    { department: "Cundinamarca", city: "Quebradanegra" },
    { department: "Cundinamarca", city: "Quetame" },
    { department: "Cundinamarca", city: "Quipile" },
    { department: "Cundinamarca", city: "Apulo" },
    { department: "Cundinamarca", city: "Ricaurte" },
    { department: "Bolívar", city: "Zambrano" },
    { department: "Cundinamarca", city: "San Bernardo" },
    { department: "Cundinamarca", city: "San Cayetano" },
    { department: "Cundinamarca", city: "San Francisco" },
    { department: "Boyacá", city: "La Uvita" },
    { department: "Cundinamarca", city: "Zipaquirá" },
    { department: "Cundinamarca", city: "Sesquilé" },
    { department: "Cundinamarca", city: "Sibaté" },
    { department: "Cundinamarca", city: "Silvania" },
    { department: "Cundinamarca", city: "Simijaca" },
    { department: "Cundinamarca", city: "Soacha" },
    { department: "Cundinamarca", city: "Subachoque" },
    { department: "Cundinamarca", city: "Suesca" },
    { department: "Cundinamarca", city: "Supatá" },
    { department: "Cundinamarca", city: "Susa" },
    { department: "Cundinamarca", city: "Sutatausa" },
    { department: "Cundinamarca", city: "Tabio" },
    { department: "Quindío", city: "Génova" },
    { department: "Cundinamarca", city: "Tausa" },
    { department: "Cundinamarca", city: "Tena" },
    { department: "Cundinamarca", city: "Tenjo" },
    { department: "Cundinamarca", city: "Tibacuy" },
    { department: "Cundinamarca", city: "Tibirita" },
    { department: "Cundinamarca", city: "Tocaima" },
    { department: "Cundinamarca", city: "Tocancipá" },
    { department: "Cundinamarca", city: "Topaipí" },
    { department: "Cundinamarca", city: "Ubalá" },
    { department: "Cundinamarca", city: "Ubaque" },
    { department: "Tolima", city: "Suárez" },
    { department: "Cundinamarca", city: "Une" },
    { department: "Cundinamarca", city: "Útica" },
    { department: "Meta", city: "Castilla la Nueva" },
    { department: "Cundinamarca", city: "Vianí" },
    { department: "Cundinamarca", city: "Villagómez" },
    { department: "Cundinamarca", city: "Villapinzón" },
    { department: "Cundinamarca", city: "Villeta" },
    { department: "Cundinamarca", city: "Viotá" },
    { department: "Cundinamarca", city: "Zipacón" },
    { department: "Chocó", city: "Quibdó" },
    { department: "Chocó", city: "Acandí" },
    { department: "Chocó", city: "Alto Baudo" },
    { department: "Chocó", city: "Atrato" },
    { department: "Chocó", city: "Bagadó" },
    { department: "Chocó", city: "Bahía Solano" },
    { department: "Chocó", city: "Bajo Baudó" },
    { department: "Boyacá", city: "Belén" },
    { department: "Chocó", city: "Bojaya" },
    { department: "Chocó", city: "Unión Panamericana" },
    { department: "Magdalena", city: "Pueblo Viejo" },
    { department: "Chocó", city: "Cértegui" },
    { department: "Chocó", city: "Condoto" },
    { department: "Putumayo", city: "Villagarzón" },
    { department: "Cundinamarca", city: "Facatativá" },
    { department: "Chocó", city: "Juradó" },
    { department: "Chocó", city: "Lloró" },
    { department: "Chocó", city: "Medio Atrato" },
    { department: "Chocó", city: "Medio Baudó" },
    { department: "Chocó", city: "Medio San Juan" },
    { department: "Chocó", city: "Nóvita" },
    { department: "Chocó", city: "Nuquí" },
    { department: "Chocó", city: "Río Iro" },
    { department: "Chocó", city: "Río Quito" },
    { department: "Chocó", city: "Riosucio" },
    { department: "Córdoba", city: "Puerto Libertador" },
    { department: "Chocó", city: "Sipí" },
    { department: "Chocó", city: "Unguía" },
    { department: "Huila", city: "Neiva" },
    { department: "Huila", city: "Acevedo" },
    { department: "Huila", city: "Agrado" },
    { department: "Huila", city: "Aipe" },
    { department: "Huila", city: "Algeciras" },
    { department: "Huila", city: "Altamira" },
    { department: "Huila", city: "Baraya" },
    { department: "Huila", city: "Campoalegre" },
    { department: "Huila", city: "Colombia" },
    { department: "Huila", city: "Elías" },
    { department: "Huila", city: "Garzón" },
    { department: "Huila", city: "Gigante" },
    { department: "Huila", city: "Guadalupe" },
    { department: "Huila", city: "Hobo" },
    { department: "Huila", city: "Iquira" },
    { department: "Huila", city: "Isnos" },
    { department: "Huila", city: "La Argentina" },
    { department: "Huila", city: "La Plata" },
    { department: "Caldas", city: "Marquetalia" },
    { department: "Huila", city: "Nátaga" },
    { department: "Huila", city: "Oporapa" },
    { department: "Huila", city: "Paicol" },
    { department: "Huila", city: "Palermo" },
    { department: "Huila", city: "Palestina" },
    { department: "Huila", city: "Pital" },
    { department: "Huila", city: "Pitalito" },
    { department: "Huila", city: "Rivera" },
    { department: "Huila", city: "Saladoblanco" },
    { department: "Nariño", city: "Arboleda" },
    { department: "Huila", city: "Santa María" },
    { department: "Huila", city: "Suaza" },
    { department: "Huila", city: "Tarqui" },
    { department: "Huila", city: "Tesalia" },
    { department: "Huila", city: "Tello" },
    { department: "Huila", city: "Teruel" },
    { department: "Huila", city: "Timaná" },
    { department: "Huila", city: "Villavieja" },
    { department: "Huila", city: "Yaguará" },
    { department: "La Guajira", city: "Riohacha" },
    { department: "La Guajira", city: "Albania" },
    { department: "La Guajira", city: "Barrancas" },
    { department: "La Guajira", city: "Dibula" },
    { department: "La Guajira", city: "Distracción" },
    { department: "La Guajira", city: "El Molino" },
    { department: "La Guajira", city: "Fonseca" },
    { department: "La Guajira", city: "Hatonuevo" },
    { department: "La Guajira", city: "Maicao" },
    { department: "La Guajira", city: "Manaure" },
    { department: "La Guajira", city: "Uribia" },
    { department: "La Guajira", city: "Urumita" },
    { department: "La Guajira", city: "Villanueva" },
    { department: "Magdalena", city: "Santa Marta" },
    { department: "Magdalena", city: "Algarrobo" },
    { department: "Magdalena", city: "Aracataca" },
    { department: "Magdalena", city: "Ariguaní" },
    { department: "Magdalena", city: "Cerro San Antonio" },
    { department: "Magdalena", city: "Chivolo" },
    { department: "Magdalena", city: "Concordia" },
    { department: "Magdalena", city: "El Banco" },
    { department: "Magdalena", city: "El Piñon" },
    { department: "Magdalena", city: "El Retén" },
    { department: "Magdalena", city: "Fundación" },
    { department: "Magdalena", city: "Guamal" },
    { department: "Magdalena", city: "Nueva Granada" },
    { department: "Magdalena", city: "Pedraza" },
    { department: "Magdalena", city: "Pivijay" },
    { department: "Magdalena", city: "Plato" },
    { department: "Magdalena", city: "Remolino" },
    { department: "Magdalena", city: "Salamina" },
    { department: "Magdalena", city: "San Zenón" },
    { department: "Magdalena", city: "Santa Ana" },
    { department: "Magdalena", city: "Sitionuevo" },
    { department: "Magdalena", city: "Tenerife" },
    { department: "Magdalena", city: "Zapayán" },
    { department: "Magdalena", city: "Zona Bananera" },
    { department: "Meta", city: "Villavicencio" },
    { department: "Meta", city: "Acacias" },
    { department: "Meta", city: "Cabuyaro" },
    { department: "Meta", city: "Cubarral" },
    { department: "Meta", city: "Cumaral" },
    { department: "Meta", city: "El Calvario" },
    { department: "Meta", city: "El Castillo" },
    { department: "Meta", city: "El Dorado" },
    { department: "Valle del Cauca", city: "Buenaventura" },
    { department: "Meta", city: "Granada" },
    { department: "Meta", city: "Guamal" },
    { department: "Meta", city: "Mapiripán" },
    { department: "Meta", city: "Mesetas" },
    { department: "Meta", city: "La Macarena" },
    { department: "Meta", city: "Uribe" },
    { department: "Meta", city: "Lejanías" },
    { department: "Meta", city: "Puerto Concordia" },
    { department: "Meta", city: "Puerto Gaitán" },
    { department: "Meta", city: "Puerto López" },
    { department: "Meta", city: "Puerto Lleras" },
    { department: "Meta", city: "Puerto Rico" },
    { department: "Meta", city: "Restrepo" },
    { department: "Magdalena", city: "Ciénaga" },
    { department: "Atlántico", city: "Ponedera" },
    { department: "Meta", city: "San Juanito" },
    { department: "Meta", city: "San Martín" },
    { department: "Meta", city: "Vista Hermosa" },
    { department: "Nariño", city: "Pasto" },
    { department: "Nariño", city: "Albán" },
    { department: "Nariño", city: "Aldana" },
    { department: "Nariño", city: "Ancuyá" },
    { department: "Boyacá", city: "Tununguá" },
    { department: "Nariño", city: "Barbacoas" },
    { department: "Boyacá", city: "Motavita" },
    { department: "Córdoba", city: "San Bernardo del Viento" },
    { department: "Nariño", city: "Colón" },
    { department: "Nariño", city: "Consaca" },
    { department: "Nariño", city: "Contadero" },
    { department: "Nariño", city: "Córdoba" },
    { department: "Nariño", city: "Cuaspud" },
    { department: "Nariño", city: "Cumbal" },
    { department: "Nariño", city: "Cumbitara" },
    { department: "Nariño", city: "El Charco" },
    { department: "Nariño", city: "El Peñol" },
    { department: "Nariño", city: "El Rosario" },
    { department: "Chocó", city: "Istmina" },
    { department: "Nariño", city: "El Tambo" },
    { department: "Nariño", city: "Funes" },
    { department: "Nariño", city: "Guachucal" },
    { department: "Nariño", city: "Guaitarilla" },
    { department: "Nariño", city: "Gualmatán" },
    { department: "Nariño", city: "Iles" },
    { department: "Nariño", city: "Imués" },
    { department: "Nariño", city: "Ipiales" },
    { department: "Nariño", city: "La Cruz" },
    { department: "Nariño", city: "La Florida" },
    { department: "Nariño", city: "La Llanada" },
    { department: "Nariño", city: "La Tola" },
    { department: "Nariño", city: "La Unión" },
    { department: "Nariño", city: "Leiva" },
    { department: "Nariño", city: "Linares" },
    { department: "Nariño", city: "Los Andes" },
    { department: "Nariño", city: "Magüí" },
    { department: "Nariño", city: "Mallama" },
    { department: "Nariño", city: "Mosquera" },
    { department: "Nariño", city: "Nariño" },
    { department: "Nariño", city: "Olaya Herrera" },
    { department: "Nariño", city: "Ospina" },
    { department: "Nariño", city: "Francisco Pizarro" },
    { department: "Nariño", city: "Policarpa" },
    { department: "Nariño", city: "Potosí" },
    { department: "Nariño", city: "Providencia" },
    { department: "Nariño", city: "Puerres" },
    { department: "Nariño", city: "Pupiales" },
    { department: "Nariño", city: "Ricaurte" },
    { department: "Nariño", city: "Roberto Payán" },
    { department: "Nariño", city: "Samaniego" },
    { department: "Nariño", city: "Sandoná" },
    { department: "Nariño", city: "San Bernardo" },
    { department: "Nariño", city: "San Lorenzo" },
    { department: "Nariño", city: "San Pablo" },
    { department: "Antioquia", city: "Belmira" },
    { department: "Boyacá", city: "Ciénega" },
    { department: "Nariño", city: "Santa Bárbara" },
    { department: "Nariño", city: "Sapuyes" },
    { department: "Nariño", city: "Taminango" },
    { department: "Nariño", city: "Tangua" },
    { department: "Nariño", city: "Santacruz" },
    { department: "Nariño", city: "Túquerres" },
    { department: "Nariño", city: "Yacuanquer" },
    { department: "Santander", city: "Puerto Wilches" },
    { department: "Santander", city: "Puerto Parra" },
    { department: "Quindío", city: "Armenia" },
    { department: "Quindío", city: "Buenavista" },
    { department: "Quindío", city: "Circasia" },
    { department: "Quindío", city: "Córdoba" },
    { department: "Quindío", city: "Filandia" },
    { department: "Quindío", city: "La Tebaida" },
    { department: "Quindío", city: "Montenegro" },
    { department: "Quindío", city: "Pijao" },
    { department: "Quindío", city: "Quimbaya" },
    { department: "Quindío", city: "Salento" },
    { department: "Risaralda", city: "Pereira" },
    { department: "Risaralda", city: "Apía" },
    { department: "Risaralda", city: "Balboa" },
    { department: "Risaralda", city: "Dosquebradas" },
    { department: "Risaralda", city: "Guática" },
    { department: "Risaralda", city: "La Celia" },
    { department: "Risaralda", city: "La Virginia" },
    { department: "Risaralda", city: "Marsella" },
    { department: "Risaralda", city: "Mistrató" },
    { department: "Risaralda", city: "Pueblo Rico" },
    { department: "Risaralda", city: "Quinchía" },
    { department: "Risaralda", city: "Santuario" },
    { department: "Santander", city: "Bucaramanga" },
    { department: "Santander", city: "Aguada" },
    { department: "Santander", city: "Albania" },
    { department: "Santander", city: "Aratoca" },
    { department: "Santander", city: "Barbosa" },
    { department: "Santander", city: "Barichara" },
    { department: "Santander", city: "Barrancabermeja" },
    { department: "Santander", city: "Betulia" },
    { department: "Santander", city: "Bolívar" },
    { department: "Santander", city: "Cabrera" },
    { department: "Santander", city: "California" },
    { department: "Santander", city: "Carcasí" },
    { department: "Santander", city: "Cepitá" },
    { department: "Santander", city: "Cerrito" },
    { department: "Santander", city: "Charalá" },
    { department: "Santander", city: "Charta" },
    { department: "Santander", city: "Chipatá" },
    { department: "Santander", city: "Cimitarra" },
    { department: "Santander", city: "Concepción" },
    { department: "Santander", city: "Confines" },
    { department: "Santander", city: "Contratación" },
    { department: "Santander", city: "Coromoro" },
    { department: "Santander", city: "Curití" },
    { department: "Santander", city: "El Guacamayo" },
    { department: "Santander", city: "El Playón" },
    { department: "Santander", city: "Encino" },
    { department: "Santander", city: "Enciso" },
    { department: "Santander", city: "Florián" },
    { department: "Santander", city: "Floridablanca" },
    { department: "Santander", city: "Galán" },
    { department: "Santander", city: "Gambita" },
    { department: "Santander", city: "Girón" },
    { department: "Santander", city: "Guaca" },
    { department: "Santander", city: "Guadalupe" },
    { department: "Santander", city: "Guapotá" },
    { department: "Santander", city: "Guavatá" },
    { department: "Santander", city: "Güepsa" },
    { department: "Santander", city: "Jesús María" },
    { department: "Santander", city: "Jordán" },
    { department: "Santander", city: "La Belleza" },
    { department: "Santander", city: "Landázuri" },
    { department: "Santander", city: "La Paz" },
    { department: "Santander", city: "Lebríja" },
    { department: "Santander", city: "Los Santos" },
    { department: "Santander", city: "Macaravita" },
    { department: "Santander", city: "Málaga" },
    { department: "Santander", city: "Matanza" },
    { department: "Santander", city: "Mogotes" },
    { department: "Santander", city: "Molagavita" },
    { department: "Santander", city: "Ocamonte" },
    { department: "Santander", city: "Oiba" },
    { department: "Santander", city: "Onzaga" },
    { department: "Santander", city: "Palmar" },
    { department: "Santander", city: "Páramo" },
    { department: "Santander", city: "Piedecuesta" },
    { department: "Santander", city: "Pinchote" },
    { department: "Santander", city: "Puente Nacional" },
    { department: "Santander", city: "Rionegro" },
    { department: "Santander", city: "San Andrés" },
    { department: "Santander", city: "San Gil" },
    { department: "Santander", city: "San Joaquín" },
    { department: "Santander", city: "San Miguel" },
    { department: "Santander", city: "Santa Bárbara" },
    { department: "Santander", city: "Simacota" },
    { department: "Santander", city: "Socorro" },
    { department: "Santander", city: "Suaita" },
    { department: "Santander", city: "Sucre" },
    { department: "Santander", city: "Suratá" },
    { department: "Santander", city: "Tona" },
    { department: "Santander", city: "Vélez" },
    { department: "Santander", city: "Vetas" },
    { department: "Santander", city: "Villanueva" },
    { department: "Santander", city: "Zapatoca" },
    { department: "Sucre", city: "Sincelejo" },
    { department: "Sucre", city: "Buenavista" },
    { department: "Sucre", city: "Caimito" },
    { department: "Sucre", city: "Coloso" },
    { department: "Sucre", city: "Coveñas" },
    { department: "Sucre", city: "Chalán" },
    { department: "Sucre", city: "El Roble" },
    { department: "Sucre", city: "Galeras" },
    { department: "Sucre", city: "Guaranda" },
    { department: "Sucre", city: "La Unión" },
    { department: "Sucre", city: "Los Palmitos" },
    { department: "Sucre", city: "Majagual" },
    { department: "Sucre", city: "Morroa" },
    { department: "Sucre", city: "Ovejas" },
    { department: "Sucre", city: "Palmito" },
    { department: "Sucre", city: "San Benito Abad" },
    { department: "Sucre", city: "San Marcos" },
    { department: "Sucre", city: "San Onofre" },
    { department: "Sucre", city: "San Pedro" },
    { department: "Sucre", city: "Sucre" },
    { department: "Sucre", city: "Tolú Viejo" },
    { department: "Tolima", city: "Alpujarra" },
    { department: "Tolima", city: "Alvarado" },
    { department: "Tolima", city: "Ambalema" },
    { department: "Tolima", city: "Armero" },
    { department: "Tolima", city: "Ataco" },
    { department: "Tolima", city: "Cajamarca" },
    { department: "Tolima", city: "Chaparral" },
    { department: "Tolima", city: "Coello" },
    { department: "Tolima", city: "Coyaima" },
    { department: "Tolima", city: "Cunday" },
    { department: "Tolima", city: "Dolores" },
    { department: "Tolima", city: "Espinal" },
    { department: "Tolima", city: "Falan" },
    { department: "Tolima", city: "Flandes" },
    { department: "Tolima", city: "Fresno" },
    { department: "Tolima", city: "Guamo" },
    { department: "Tolima", city: "Herveo" },
    { department: "Tolima", city: "Honda" },
    { department: "Tolima", city: "Icononzo" },
    { department: "Tolima", city: "Mariquita" },
    { department: "Tolima", city: "Melgar" },
    { department: "Tolima", city: "Murillo" },
    { department: "Tolima", city: "Natagaima" },
    { department: "Tolima", city: "Ortega" },
    { department: "Tolima", city: "Palocabildo" },
    { department: "Tolima", city: "Piedras" },
    { department: "Tolima", city: "Planadas" },
    { department: "Tolima", city: "Prado" },
    { department: "Tolima", city: "Purificación" },
    { department: "Tolima", city: "Rio Blanco" },
    { department: "Tolima", city: "Roncesvalles" },
    { department: "Tolima", city: "Rovira" },
    { department: "Tolima", city: "Saldaña" },
    { department: "Tolima", city: "Santa Isabel" },
    { department: "Tolima", city: "Venadillo" },
    { department: "Tolima", city: "Villahermosa" },
    { department: "Tolima", city: "Villarrica" },
    { department: "Arauca", city: "Arauquita" },
    { department: "Arauca", city: "Cravo Norte" },
    { department: "Arauca", city: "Fortul" },
    { department: "Arauca", city: "Puerto Rondón" },
    { department: "Arauca", city: "Saravena" },
    { department: "Arauca", city: "Tame" },
    { department: "Arauca", city: "Arauca" },
    { department: "Casanare", city: "Yopal" },
    { department: "Casanare", city: "Aguazul" },
    { department: "Casanare", city: "Chámeza" },
    { department: "Casanare", city: "Hato Corozal" },
    { department: "Casanare", city: "La Salina" },
    { department: "Casanare", city: "Monterrey" },
    { department: "Casanare", city: "Pore" },
    { department: "Casanare", city: "Recetor" },
    { department: "Casanare", city: "Sabanalarga" },
    { department: "Casanare", city: "Sácama" },
    { department: "Casanare", city: "Tauramena" },
    { department: "Casanare", city: "Trinidad" },
    { department: "Casanare", city: "Villanueva" },
    { department: "Putumayo", city: "Mocoa" },
    { department: "Putumayo", city: "Colón" },
    { department: "Putumayo", city: "Orito" },
    { department: "Putumayo", city: "Puerto Caicedo" },
    { department: "Putumayo", city: "Puerto Guzmán" },
    { department: "Putumayo", city: "Leguízamo" },
    { department: "Putumayo", city: "Sibundoy" },
    { department: "Putumayo", city: "San Francisco" },
    { department: "Putumayo", city: "San Miguel" },
    { department: "Putumayo", city: "Santiago" },
    { department: "Amazonas", city: "Leticia" },
    { department: "Amazonas", city: "El Encanto" },
    { department: "Amazonas", city: "La Chorrera" },
    { department: "Amazonas", city: "La Pedrera" },
    { department: "Amazonas", city: "La Victoria" },
    { department: "Amazonas", city: "Puerto Arica" },
    { department: "Amazonas", city: "Puerto Nariño" },
    { department: "Amazonas", city: "Puerto Santander" },
    { department: "Amazonas", city: "Tarapacá" },
    { department: "Guainía", city: "Inírida" },
    { department: "Guainía", city: "Barranco Minas" },
    { department: "Guainía", city: "Mapiripana" },
    { department: "Guainía", city: "San Felipe" },
    { department: "Guainía", city: "Puerto Colombia" },
    { department: "Guainía", city: "La Guadalupe" },
    { department: "Guainía", city: "Cacahual" },
    { department: "Guainía", city: "Pana Pana" },
    { department: "Guainía", city: "Morichal" },
    { department: "Vaupés", city: "Mitú" },
    { department: "Vaupés", city: "Caruru" },
    { department: "Vaupés", city: "Pacoa" },
    { department: "Vaupés", city: "Taraira" },
    { department: "Vaupés", city: "Papunaua" },
    { department: "Vichada", city: "Puerto Carreño" },
    { department: "Vichada", city: "La Primavera" },
    { department: "Vichada", city: "Santa Rosalía" },
    { department: "Vichada", city: "Cumaribo" },
    { department: "Caquetá", city: "San José del Fragua" },
    { department: "Meta", city: "Barranca de Upía" },
    { department: "Santander", city: "Palmas del Socorro" },
    { department: "Cundinamarca", city: "San Juan de Río Seco" },
    { department: "Atlántico", city: "Juan de Acosta" },
    { department: "Meta", city: "Fuente de Oro" },
    { department: "Casanare", city: "San Luis de Gaceno" },
    { department: "Chocó", city: "El Litoral del San Juan" },
    { department: "Cundinamarca", city: "Villa de San Diego de Ubate" },
    { department: "Bolívar", city: "Barranco de Loba" },
    { department: "Boyacá", city: "Togüí" },
    { department: "Bolívar", city: "Santa Rosa del Sur" },
    { department: "Chocó", city: "El Cantón del San Pablo" },
    { department: "Boyacá", city: "Villa de Leyva" },
    { department: "Magdalena", city: "San Sebastián de Buenavista" },
    { department: "Boyacá", city: "Paz de Río" },
    { department: "Bolívar", city: "Hatillo de Loba" },
    { department: "Magdalena", city: "Sabanas de San Angel" },
    { department: "Guaviare", city: "Calamar" },
    { department: "Cesar", city: "Río de Oro" },
    { department: "Antioquia", city: "San Pedro de Uraba" },
    { department: "Guaviare", city: "San José del Guaviare" },
    { department: "Boyacá", city: "Santa Rosa de Viterbo" },
    { department: "Cauca", city: "Santander de Quilichao" },
    { department: "Guaviare", city: "Miraflores" },
    { department: "Antioquia", city: "Santafé de Antioquia" },
    { department: "Meta", city: "San Carlos de Guaroa" },
    { department: "Atlántico", city: "Palmar de Varela" },
    { department: "Antioquia", city: "Santa Rosa de Osos" },
    { department: "Antioquia", city: "San Andrés de Cuerquía" },
    { department: "Tolima", city: "Valle de San Juan" },
    { department: "Santander", city: "San Vicente de Chucurí" },
    { department: "Santander", city: "San José de Miranda" },
    {
        department: "Archipiélago de San Andrés, Providencia y Santa Catalina",
        city: "Providencia",
    },
    { department: "Risaralda", city: "Santa Rosa de Cabal" },
    { department: "Cundinamarca", city: "Guayabal de Siquima" },
    { department: "Caquetá", city: "Belén de Los Andaquies" },
    { department: "Casanare", city: "Paz de Ariporo" },
    { department: "Santander", city: "Santa Helena del Opón" },
    { department: "Boyacá", city: "San Pablo de Borbur" },
    { department: "La Guajira", city: "La Jagua del Pilar" },
    { department: "Cesar", city: "La Jagua de Ibirico" },
    { department: "Sucre", city: "San Luis de Sincé" },
    { department: "Boyacá", city: "San Luis de Gaceno" },
    { department: "Bolívar", city: "El Carmen de Bolívar" },
    { department: "Chocó", city: "El Carmen de Atrato" },
    { department: "Sucre", city: "San Juan de Betulia" },
    { department: "Magdalena", city: "Pijiño del Carmen" },
    { department: "Antioquia", city: "Vigía del Fuerte" },
    { department: "Bolívar", city: "San Martín de Loba" },
    { department: "Bolívar", city: "Altos del Rosario" },
    { department: "Tolima", city: "Carmen de Apicala" },
    { department: "Cundinamarca", city: "San Antonio del Tequendama" },
    { department: "Santander", city: "Sabana de Torres" },
    { department: "Guaviare", city: "El Retorno" },
    { department: "Córdoba", city: "San José de Uré" },
    { department: "Nariño", city: "San Pedro de Cartago" },
    { department: "Atlántico", city: "Campo de La Cruz" },
    { department: "Meta", city: "San Juan de Arama" },
    { department: "Antioquia", city: "San José de La Montaña" },
    { department: "Caquetá", city: "Cartagena del Chairá" },
    { department: "Chocó", city: "San José del Palmar" },
    { department: "Cundinamarca", city: "Agua de Dios" },
    { department: "Bolívar", city: "San Jacinto del Cauca" },
    { department: "Huila", city: "San Agustín" },
    { department: "Nariño", city: "El Tablón de Gómez" },
    {
        department: "Archipiélago de San Andrés, Providencia y Santa Catalina",
        city: "San Andrés",
    },
    { department: "Boyacá", city: "San José de Pare" },
    { department: "Putumayo", city: "Valle de Guamez" },
    { department: "Bolívar", city: "San Pablo de Borbur" },
    { department: "Sucre", city: "Santiago de Tolú" },
    { department: "Bogotá D.C.", city: "Bogotá D.C." },
    { department: "Cundinamarca", city: "Carmen de Carupa" },
    { department: "Córdoba", city: "Ciénaga de Oro" },
    { department: "Antioquia", city: "San Juan de Urabá" },
    { department: "La Guajira", city: "San Juan del Cesar" },
    { department: "Santander", city: "El Carmen de Chucurí" },
    { department: "Antioquia", city: "El Carmen de Viboral" },
    { department: "Risaralda", city: "Belén de Umbría" },
    { department: "Chocó", city: "Belén de Bajira" },
    { department: "Santander", city: "Valle de San José" },
    { department: "Tolima", city: "San Luis" },
    { department: "Boyacá", city: "San Miguel de Sema" },
    { department: "Tolima", city: "San Antonio" },
    { department: "Santander", city: "San Benito" },
    { department: "Cundinamarca", city: "Vergara" },
    { department: "Córdoba", city: "San Carlos" },
    { department: "Amazonas", city: "Puerto Alegría" },
    { department: "Santander", city: "Hato" },
    { department: "Bolívar", city: "San Jacinto" },
    { department: "Cauca", city: "San Sebastián" },
    { department: "Antioquia", city: "San Carlos" },
    { department: "Boyacá", city: "Tuta" },
    { department: "Norte de Santander", city: "Silos" },
    { department: "Norte de Santander", city: "Cácota" },
    { department: "Valle del Cauca", city: "El Dovio" },
    { department: "Norte de Santander", city: "Toledo" },
    { department: "Valle del Cauca", city: "Roldanillo" },
    { department: "Norte de Santander", city: "Mutiscua" },
    { department: "Valle del Cauca", city: "Argelia" },
    { department: "Norte de Santander", city: "El Zulia" },
    { department: "Norte de Santander", city: "Salazar" },
    { department: "Valle del Cauca", city: "Sevilla" },
    { department: "Valle del Cauca", city: "Zarzal" },
    { department: "Norte de Santander", city: "Cucutilla" },
    { department: "Valle del Cauca", city: "El Cerrito" },
    { department: "Valle del Cauca", city: "Cartago" },
    { department: "Valle del Cauca", city: "Caicedonia" },
    { department: "Norte de Santander", city: "Puerto Santander" },
    { department: "Norte de Santander", city: "Gramalote" },
    { department: "Valle del Cauca", city: "El Cairo" },
    { department: "Norte de Santander", city: "El Tarra" },
    { department: "Valle del Cauca", city: "La Unión" },
    { department: "Valle del Cauca", city: "Restrepo" },
    { department: "Norte de Santander", city: "Teorama" },
    { department: "Valle del Cauca", city: "Dagua" },
    { department: "Norte de Santander", city: "Arboledas" },
    { department: "Valle del Cauca", city: "Guacarí" },
    { department: "Norte de Santander", city: "Lourdes" },
    { department: "Valle del Cauca", city: "Ansermanuevo" },
    { department: "Norte de Santander", city: "Bochalema" },
    { department: "Valle del Cauca", city: "Bugalagrande" },
    { department: "Norte de Santander", city: "Convención" },
    { department: "Norte de Santander", city: "Hacarí" },
    { department: "Valle del Cauca", city: "La Victoria" },
    { department: "Norte de Santander", city: "Herrán" },
    { department: "Valle del Cauca", city: "Ginebra" },
    { department: "Valle del Cauca", city: "Yumbo" },
    { department: "Valle del Cauca", city: "Obando" },
    { department: "Norte de Santander", city: "Tibú" },
    { department: "Norte de Santander", city: "San Cayetano" },
    { department: "Norte de Santander", city: "San Calixto" },
    { department: "Valle del Cauca", city: "Bolívar" },
    { department: "Norte de Santander", city: "La Playa" },
    { department: "Valle del Cauca", city: "Cali" },
    { department: "Valle del Cauca", city: "San Pedro" },
    { department: "Valle del Cauca", city: "Guadalajara de Buga" },
    { department: "Norte de Santander", city: "Chinácota" },
    { department: "Norte de Santander", city: "Ragonvalia" },
    { department: "Norte de Santander", city: "La Esperanza" },
    { department: "Norte de Santander", city: "Villa del Rosario" },
    { department: "Norte de Santander", city: "Chitagá" },
    { department: "Valle del Cauca", city: "Calima" },
    { department: "Norte de Santander", city: "Sardinata" },
    { department: "Valle del Cauca", city: "Andalucía" },
    { department: "Valle del Cauca", city: "Pradera" },
    { department: "Norte de Santander", city: "Abrego" },
    { department: "Norte de Santander", city: "Los Patios" },
    { department: "Norte de Santander", city: "Ocaña" },
    { department: "Norte de Santander", city: "Bucarasica" },
    { department: "Valle del Cauca", city: "Yotoco" },
    { department: "Valle del Cauca", city: "Palmira" },
    { department: "Valle del Cauca", city: "Riofrío" },
    { department: "Norte de Santander", city: "Santiago" },
    { department: "Valle del Cauca", city: "Alcalá" },
    { department: "Valle del Cauca", city: "Versalles" },
    { department: "Norte de Santander", city: "Labateca" },
    { department: "Norte de Santander", city: "Cachirá" },
    { department: "Norte de Santander", city: "Villa Caro" },
    { department: "Norte de Santander", city: "Durania" },
    { department: "Valle del Cauca", city: "El Águila" },
    { department: "Valle del Cauca", city: "Toro" },
    { department: "Valle del Cauca", city: "Candelaria" },
    { department: "Valle del Cauca", city: "La Cumbre" },
    { department: "Valle del Cauca", city: "Ulloa" },
    { department: "Valle del Cauca", city: "Trujillo" },
    { department: "Valle del Cauca", city: "Vijes" },
];
